<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SpotifeiFamilia.Data\SpotifeiFamilia.Data.csproj" />
    <ProjectReference Include="..\SpotifeiFamilia.Model\SpotifeiFamilia.Model.csproj" />
    <ProjectReference Include="..\SpotifeiFamilia.Service\SpotifeiFamilia.Service.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
